### ISSUE TITLE
How add has_paper_trail to comments model

### ISSUE THREAD

**Issue by josercarmo** [yhirano55/active_admin_versioning#17]
I would like to add has_paper_trail to the model comments of activeadmin, how to do this, if the model is inside the gem active admin? Thank you!!

**Comment by yhirano55** [comment]
Did you try to write monkey patch like this?

```ruby
if defined?(ActiveAdmin::Comment)
  ActiveAdmin::Comment.class_eval do
    has_paper_trail
  end
end
```

**Comment by josercarmo** [comment]
Thanks!
